package battlenet

import (
	"errors"
	"strings"
)

var url = func(s string) string {
	r := strings.ToLower(region)

	if r == "cn" {
		return "https://www.battlenet.com.cn/oauth/" + s
	}
	if r == "us" || r == "eu" || r == "apac" {
		return "https://" + r + ".battle.net/oauth/" + s
	}
	return "https://us.battle.net/oauth/" + s
}

var (
	EndpointOauth2 = func(endpoint string) string {
		if "token" != endpoint && "authorize" != endpoint {
			panic(errors.New("Can't resolve endpoint."))
		}

		r := strings.ToLower(region)

		switch r {
		case "us":
		case "eu":
		case "kr":
		case "tw":
		case "sea":
			return "https://" + r + ".battle.net/oauth/" + endpoint
		case "cn":
			return "https://www.battlenet.com.cn/oauth/" + endpoint
		default:
			return "https://us.battle.net/oauth/" + endpoint
		}
		return "https://us.battle.net/oauth/" + endpoint
	}

	EndpointAPI = func() string {
		r := strings.ToLower(region)
		switch r {
		case "us":
		case "eu":
		case "kr":
		case "tw":
		case "sea":
			return "https://" + r + ".api.battle.net/"
		case "cn":
			return "https://api.battlenet.com.cn/"
		default:
			return "https://us.api.battle.net/"
		}
		return "https://us.api.battle.net/"
	}

	EndpointAuthURL  = EndpointOauth2("authorize")
	EndpointTokenURL = EndpointOauth2("token")

	EndpointWow = EndpointAPI() + "wow/"

	/*
		COMMUNITY OAUTH PROFILE API
		------------------------------------------------------------

		ACCOUNT
		GET USER /ACCOUNT/USER

		PROFILE
		GET SC2 OAUTH PROFILE /SC2/PROFILE/USER
		GET WOW OAUTH PROFILE /WOW/USER/CHARACTERS

	*/

	/*
		WOW API
		------------------------------------------------------------

		ACHIEVEMENT
		GET ACHIEVEMENT /WOW/ACHIEVEMENT/:ID

		AUCTION
		GET AUCTION DATA STATUS /WOW/AUCTION/DATA/:REALM

		BOSS
		GET MASTER LIST /WOW/BOSS/
		GET BOSS /WOW/BOSS/:BOSSID

		CHALLENGE MODE
		GET REALM LEADERBOARD /WOW/CHALLENGE/:REALM
		GET REGION LEADERBOARD /WOW/CHALLENGE/REGION

		CHARACTER PROFILE
		GET CHARACTER PROFILE /WOW/CHARACTER/:REALM/:CHARACTERNAME
		GET ACHIEVEMENTS /WOW/CHARACTER/:REALM/:CHARACTERNAME
		GET APPEARANCE /WOW/CHARACTER/:REALM/:CHARACTERNAME
		GET FEED /WOW/CHARACTER/:REALM/:CHARACTERNAME
		GET GUILD /WOW/CHARACTER/:REALM/:CHARACTERNAME
		GET HUNTER PETS /WOW/CHARACTER/:REALM/:CHARACTERNAME
		GET ITEMS /WOW/CHARACTER/:REALM/:CHARACTERNAME
		GET MOUNTS /WOW/CHARACTER/:REALM/:CHARACTERNAME
		GET PETS /WOW/CHARACTER/:REALM/:CHARACTERNAME
		GET PET SLOTS /WOW/CHARACTER/:REALM/:CHARACTERNAME
		GET PROFESSIONS /WOW/CHARACTER/:REALM/:CHARACTERNAME
		GET PROGRESSION /WOW/CHARACTER/:REALM/:CHARACTERNAME
		GET PVP /WOW/CHARACTER/:REALM/:CHARACTERNAME
		GET QUESTS /WOW/CHARACTER/:REALM/:CHARACTERNAME
		GET REPUTATION /WOW/CHARACTER/:REALM/:CHARACTERNAME
		GET STATISTICS /WOW/CHARACTER/:REALM/:CHARACTERNAME
		GET STATS /WOW/CHARACTER/:REALM/:CHARACTERNAME
		GET TALENTS /WOW/CHARACTER/:REALM/:CHARACTERNAME
		GET TITLES /WOW/CHARACTER/:REALM/:CHARACTERNAME
		GET AUDIT /WOW/CHARACTER/:REALM/:CHARACTERNAME

		GUILD PROFILE
		GET GUILD PROFILE /WOW/GUILD/:REALM/:GUILDNAME
		GET MEMBERS /WOW/GUILD/:REALM/:GUILDNAME
		GET ACHIEVEMENTS /WOW/GUILD/:REALM/:GUILDNAME
		GET NEWS /WOW/GUILD/:REALM/:GUILDNAME
		GET CHALLENGE /WOW/GUILD/:REALM/:GUILDNAME

		ITEM
		GET ITEM /WOW/ITEM/:ITEMID
		GET ITEM SET /WOW/ITEM/SET/:SETID

		MOUNT
		GET MASTER LIST /WOW/MOUNT/

		PET
		GET MASTER LIST /WOW/PET/
		GET ABILITIES /WOW/PET/ABILITY/:ABILITYID
		GET SPECIES /WOW/PET/SPECIES/:SPECIESID
		GET STATS /WOW/PET/STATS/:SPECIESID

		PVP
		GET LEADERBOARDS /WOW/LEADERBOARD/:BRACKET

		QUEST
		GET QUEST /WOW/QUEST/:QUESTID

		REALM STATUS
		GET REALM STATUS /WOW/REALM/STATUS

		RECIPE
		GET RECIPE /WOW/RECIPE/:RECIPEID

		SPELL
		GET SPELL /WOW/SPELL/:SPELLID

		ZONE
		GET MASTER LIST /WOW/ZONE/
		GET ZONE /WOW/ZONE/:ZONEID

		DATA RESOURCES
		GET BATTLEGROUPS /WOW/DATA/BATTLEGROUPS/
		GET CHARACTER RACES /WOW/DATA/CHARACTER/RACES
		GET CHARACTER CLASSES /WOW/DATA/CHARACTER/CLASSES
		GET CHARACTER ACHIEVEMENTS /WOW/DATA/CHARACTER/ACHIEVEMENTS
		GET GUILD REWARDS /WOW/DATA/GUILD/REWARDS
		GET GUILD PERKS /WOW/DATA/GUILD/PERKS
		GET GUILD ACHIEVEMENTS /WOW/DATA/GUILD/ACHIEVEMENTS
		GET ITEM CLASSES /WOW/DATA/ITEM/CLASSES
		GET TALENTS /WOW/DATA/TALENTS
		GET PET TYPES /WOW/DATA/PET/TYPES

	*/

	/*
		SC2 API
		--------------------------------------------------------------------
		PROFILE
		GET PROFILE /SC2/PROFILE/:ID/:REGION/:NAME/
		GET LADDERS /SC2/PROFILE/:ID/:REGION/:NAME/LADDERS
		GET MATCH HISTORY /SC2/PROFILE/:ID/:REGION/:NAME/MATCHES

		LADDER
		GET LADDER /SC2/LADDER/:ID

		DATA RESOURCES
		GET ACHIEVEMENTS /SC2/DATA/ACHIEVEMENTS
		GET REWARDS /SC2/DATA/REWARDS

	*/

	/*
		WOW GAME DATA API
		--------------------------------------------------------------------
		CONNECTED REALM
		GET GETCONNECTEDREALMINDEX /CONNECTED-REALM/
		GET GETCONNECTEDREALM /CONNECTED-REALM/{CONNECTEDREALMID}

		MYTHIC KEYSTONE LEADERBOARD
		GET GETMYTHICLEADERBOARDINDEX /CONNECTED-REALM/{CONNECTEDREALMID}/MYTHIC-LEADERBOARD/
		GET GETMYTHICLEADERBOARD /CONNECTED-REALM/{CONNECTEDREALMID}/MYTHIC-LEADERBOARD/{DUNGEONID}/PERIOD/{PERIOD}

		MYTHIC CHALLENGE MODE
		GET GETMYTHICCHALLENGEMODEINDEX /MYTHIC-CHALLENGE-MODE/

		PLAYABLE CLASS
		GET GETPLAYABLECLASSESINDEX /PLAYABLE-CLASS/
		GET GETPLAYABLECLASS /PLAYABLE-CLASS/{CLASSID}

		PLAYABLE SPECIALIZATION
		GET GETPLAYABLESPECIALIZATIONINDEX /PLAYABLE-SPECIALIZATION/
		GET GETPLAYABLESPECIALIZATION /PLAYABLE-SPECIALIZATION/{SPECID}

		REALM
		GET GETREALMINDEX /REALM/
		GET GETREALM /REALM/{REALMSLUG}

		REGION
		GET GETREGIONINDEX /REGION/
		GET GETREGION /REGION/{REGIONID}

		WOW TOKEN
		GET GETTOKENINDEX /TOKEN/

	*/

	/*
		D3 API
		--------------------------------------------------------------------
		D3 ACT
		GET GETACTINDEX /D3/DATA/ACT
		GET GETACT /D3/DATA/ACT/{ACTID}

		D3 ARTISAN AND RECIPE
		GET GETARTISAN /D3/DATA/ARTISAN/{ARTISANSLUG}
		GET GETRECIPE /D3/DATA/ARTISAN/{ARTISANSLUG}/RECIPE/{RECIPESLUG}

		D3 FOLLOWER
		GET GETFOLLOWER /D3/DATA/FOLLOWER/{FOLLOWERSLUG}

		D3 CHARACTER CLASS AND SKILL
		GET GETCHARACTERCLASS /D3/DATA/HERO/{CLASSSLUG}
		GET GETAPISKILL /D3/DATA/HERO/{CLASSSLUG}/SKILL/{SKILLSLUG}

		D3 ITEM TYPE
		GET GETITEMTYPEINDEX /D3/DATA/ITEM-TYPE
		GET GETITEMTYPE /D3/DATA/ITEM-TYPE/{ITEMTYPESLUG}

		D3 ITEM
		GET GETITEM /D3/DATA/ITEM/{ITEMSLUGANDID}

		D3 PROFILE
		GET GETAPIACCOUNT /D3/PROFILE/{ACCOUNT}/
		GET GETAPIHERO /D3/PROFILE/{ACCOUNT}/HERO/{HEROID}
		GET GETAPIDETAILEDHEROITEMS /D3/PROFILE/{ACCOUNT}/HERO/{HEROID}/ITEMS
		GET GETAPIDETAILEDFOLLOWERITEMS /D3/PROFILE/{ACCOUNT}/HERO/{HEROID}/FOLLOWER-ITEMS

	*/

	/*
		D3 GAME DATA API
		--------------------------------------------------------------------
		D3
		GET SEASON INDEX /DATA/D3/SEASON/
		GET SEASON /DATA/D3/SEASON/:ID
		GET SEASON LEADERBOARD /DATA/D3/SEASON/:ID/LEADERBOARD/:LEADERBOARD
		GET ERA INDEX /DATA/D3/ERA/
		GET ERA /DATA/D3/ERA/:ID
		GET ERA LEADERBOARD /DATA/D3/ERA/:ID/LEADERBOARD/:LEADERBOARD

	*/
)
