package endpoints

/*
		D3 API
		--------------------------------------------------------------------
		D3 ACT
	[ ]	GETACTINDEX /D3/DATA/ACT
	[ ]	GETACT 		/D3/DATA/ACT/{ACTID}

		D3 ARTISAN AND RECIPE
	[ ]	GETARTISAN 	/D3/DATA/ARTISAN/{ARTISANSLUG}
	[ ]	GETRECIPE 	/D3/DATA/ARTISAN/{ARTISANSLUG}/RECIPE/{RECIPESLUG}

		D3 FOLLOWER
	[ ]	GETFOLLOWER /D3/DATA/FOLLOWER/{FOLLOWERSLUG}

		D3 CHARACTER CLASS AND SKILL
	[ ]	GETCHARACTERCLASS 	/D3/DATA/HERO/{CLASSSLUG}
	[ ]	GETAPISKILL 		/D3/DATA/HERO/{CLASSSLUG}/SKILL/{SKILLSLUG}

		D3 ITEM TYPE
	[ ]	GETITEMTYPEINDEX 	/D3/DATA/ITEM-TYPE
	[ ]	GETITEMTYPE 		/D3/DATA/ITEM-TYPE/{ITEMTYPESLUG}

		D3 ITEM
	[ ]	GETITEM /D3/DATA/ITEM/{ITEMSLUGANDID}

		D3 PROFILE
	[ ]	GETAPIACCOUNT 				/D3/PROFILE/{ACCOUNT}/
	[ ]	GETAPIHERO 					/D3/PROFILE/{ACCOUNT}/HERO/{HEROID}
	[ ]	GETAPIDETAILEDHEROITEMS 	/D3/PROFILE/{ACCOUNT}/HERO/{HEROID}/ITEMS
	[ ]	GETAPIDETAILEDFOLLOWERITEMS /D3/PROFILE/{ACCOUNT}/HERO/{HEROID}/FOLLOWER-ITEMS

*/

/*
		D3 GAME DATA API
		--------------------------------------------------------------------
		D3
	[ ]	SEASON INDEX 		/DATA/D3/SEASON/
	[ ]	SEASON 				/DATA/D3/SEASON/:ID
	[ ]	SEASON LEADERBOARD 	/DATA/D3/SEASON/:ID/LEADERBOARD/:LEADERBOARD
	[ ]	ERA INDEX 			/DATA/D3/ERA/
	[ ]	ERA 				/DATA/D3/ERA/:ID
	[ ]	ERA LEADERBOARD 	/DATA/D3/ERA/:ID/LEADERBOARD/:LEADERBOARD

*/
