package endpoints

import (
	"strconv"
)

var (
	EndpointWow                  = EndpointAPI() + "wow/"
	EndpointWowUser              = EndpointWow + "user/"
	EndpointWowOauthProfile      = EndpointWowUser + "characters"
	EndpointWowAchievement       = func(id int) string { return EndpointWow + "achievement/" + strconv.Itoa(id) }
	EndpointWowAuction           = EndpointWow + "auction/"
	EndpointWowAuctionDataStatus = func(realm string) string { return EndpointWowAuction + "data/" + realm }
	EndpointWowBossMaster        = EndpointWow + "boss/"
	EndpointWowBoss              = func(id int) string { return EndpointWowBossMaster + strconv.Itoa(id) }
	EndpointWowChallenge         = EndpointWow + "challenge/"
	EndpointWowRealmLeaderboard  = func(realm string) string { return EndpointWowChallenge + realm }
	EndpointWowRegionLeaderboard = EndpointWowChallenge + "region"

/*
		WOW API
		------------------------------------------------------------
		PROFILE
	[x]	WOW OAUTH PROFILE /WOW/USER/CHARACTERS

		ACHIEVEMENT
	[x]	ACHIEVEMENT /WOW/ACHIEVEMENT/:ID

		AUCTION
	[x]	AUCTION DATA STATUS /WOW/AUCTION/DATA/:REALM

		BOSS
	[x]	MASTER LIST /WOW/BOSS/
	[x]	BOSS /WOW/BOSS/:BOSSID

		CHALLENGE MODE
	[x]	REALM LEADERBOARD /WOW/CHALLENGE/:REALM
	[x]	REGION LEADERBOARD /WOW/CHALLENGE/REGION

		CHARACTER PROFILE
	[ ]	CHARACTER PROFILE 	/WOW/CHARACTER/:REALM/:CHARACTERNAME
	[ ]	ACHIEVEMENTS 		/WOW/CHARACTER/:REALM/:CHARACTERNAME
	[ ]	APPEARANCE 			/WOW/CHARACTER/:REALM/:CHARACTERNAME
	[ ]	FEED 				/WOW/CHARACTER/:REALM/:CHARACTERNAME
	[ ]	GUILD 				/WOW/CHARACTER/:REALM/:CHARACTERNAME
	[ ]	HUNTER PETS 		/WOW/CHARACTER/:REALM/:CHARACTERNAME
	[ ]	ITEMS 				/WOW/CHARACTER/:REALM/:CHARACTERNAME
	[ ]	MOUNTS 				/WOW/CHARACTER/:REALM/:CHARACTERNAME
	[ ]	PETS 				/WOW/CHARACTER/:REALM/:CHARACTERNAME
	[ ]	PET SLOTS 			/WOW/CHARACTER/:REALM/:CHARACTERNAME
	[ ]	PROFESSIONS 		/WOW/CHARACTER/:REALM/:CHARACTERNAME
	[ ]	PROGRESSION 		/WOW/CHARACTER/:REALM/:CHARACTERNAME
	[ ]	PVP 				/WOW/CHARACTER/:REALM/:CHARACTERNAME
	[ ]	QUESTS 				/WOW/CHARACTER/:REALM/:CHARACTERNAME
	[ ]	REPUTATION 			/WOW/CHARACTER/:REALM/:CHARACTERNAME
	[ ]	STATISTICS 			/WOW/CHARACTER/:REALM/:CHARACTERNAME
	[ ]	STATS 				/WOW/CHARACTER/:REALM/:CHARACTERNAME
	[ ]	TALENTS 			/WOW/CHARACTER/:REALM/:CHARACTERNAME
	[ ]	TITLES 				/WOW/CHARACTER/:REALM/:CHARACTERNAME
	[ ]	AUDIT 				/WOW/CHARACTER/:REALM/:CHARACTERNAME

		GUILD PROFILE
	[ ]	GUILD PROFILE 	/WOW/GUILD/:REALM/:GUILDNAME
	[ ]	MEMBERS 		/WOW/GUILD/:REALM/:GUILDNAME
	[ ]	ACHIEVEMENTS 	/WOW/GUILD/:REALM/:GUILDNAME
	[ ]	NEWS 			/WOW/GUILD/:REALM/:GUILDNAME
	[ ]	CHALLENGE 		/WOW/GUILD/:REALM/:GUILDNAME

		ITEM
	[ ]	ITEM 		/WOW/ITEM/:ITEMID
	[ ]	ITEM SET 	/WOW/ITEM/SET/:SETID

		MOUNT
	[ ]	MASTER LIST /WOW/MOUNT/

		PET
	[ ]	MASTER LIST /WOW/PET/
	[ ]	ABILITIES 	/WOW/PET/ABILITY/:ABILITYID
	[ ]	SPECIES 	/WOW/PET/SPECIES/:SPECIESID
	[ ]	STATS 		/WOW/PET/STATS/:SPECIESID

		PVP
	[ ]	LEADERBOARDS /WOW/LEADERBOARD/:BRACKET

		QUEST
	[ ]	QUEST /WOW/QUEST/:QUESTID

		REALM STATUS
	[ ]	REALM STATUS /WOW/REALM/STATUS

		RECIPE
	[ ]	RECIPE /WOW/RECIPE/:RECIPEID

		SPELL
	[ ]	SPELL /WOW/SPELL/:SPELLID

		ZONE
	[ ]	MASTER LIST /WOW/ZONE/
	[ ]	ZONE 		/WOW/ZONE/:ZONEID

		DATA RESOURCES
	[ ]	BATTLEGROUPS 			/WOW/DATA/BATTLEGROUPS/
	[ ]	CHARACTER RACES 		/WOW/DATA/CHARACTER/RACES
	[ ]	CHARACTER CLASSES 		/WOW/DATA/CHARACTER/CLASSES
	[ ]	CHARACTER ACHIEVEMENTS 	/WOW/DATA/CHARACTER/ACHIEVEMENTS
	[ ]	GUILD REWARDS 			/WOW/DATA/GUILD/REWARDS
	[ ]	GUILD PERKS 			/WOW/DATA/GUILD/PERKS
	[ ]	GUILD ACHIEVEMENTS 		/WOW/DATA/GUILD/ACHIEVEMENTS
	[ ]	ITEM CLASSES 			/WOW/DATA/ITEM/CLASSES
	[ ]	TALENTS 				/WOW/DATA/TALENTS
	[ ]	PET TYPES 				/WOW/DATA/PET/TYPES

*/

/*
		WOW GAME DATA API
		--------------------------------------------------------------------
		CONNECTED REALM
	[ ]	GETCONNECTEDREALMINDEX 	/CONNECTED-REALM/
	[ ]	GETCONNECTEDREALM 		/CONNECTED-REALM/{CONNECTEDREALMID}

		MYTHIC KEYSTONE LEADERBOARD
	[ ]	GETMYTHICLEADERBOARDINDEX 	/CONNECTED-REALM/{CONNECTEDREALMID}/MYTHIC-LEADERBOARD/
	[ ]	GETMYTHICLEADERBOARD 		/CONNECTED-REALM/{CONNECTEDREALMID}/MYTHIC-LEADERBOARD/{DUNGEONID}/PERIOD/{PERIOD}

		MYTHIC CHALLENGE MODE
	[ ]	GETMYTHICCHALLENGEMODEINDEX /MYTHIC-CHALLENGE-MODE/

		PLAYABLE CLASS
	[ ]	GETPLAYABLECLASSESINDEX /PLAYABLE-CLASS/
	[ ]	GETPLAYABLECLASS 		/PLAYABLE-CLASS/{CLASSID}

		PLAYABLE SPECIALIZATION
	[ ]	GETPLAYABLESPECIALIZATIONINDEX 	/PLAYABLE-SPECIALIZATION/
	[ ]	GETPLAYABLESPECIALIZATION 		/PLAYABLE-SPECIALIZATION/{SPECID}

		REALM
	[ ]	GETREALMINDEX 	/REALM/
	[ ]	GETREALM 		/REALM/{REALMSLUG}

		REGION
	[ ]	GETREGIONINDEX 	/REGION/
	[ ]	GETREGION 		/REGION/{REGIONID}

		WOW TOKEN
	[ ]	GETTOKENINDEX /TOKEN/

*/
)
